sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.5.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose pull
  - sed -e 's/${PYTHON_VERSION}/'${PYTHON_VERSION}/g -e 's/${DJANGO_VERSION}/'${DJANGO_VERSION}/g Dockerfile.tmpl  > Dockerfile
  - docker-compose build

script: docker-compose run test

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.5.0
  matrix:
    - DJANGO_VERSION="1.8.*" PYTHON_VERSION=3.5
    - DJANGO_VERSION="1.8.*" PYTHON_VERSION=3.4
    - DJANGO_VERSION="1.8.*" PYTHON_VERSION=3.3
    - DJANGO_VERSION="1.8.*" PYTHON_VERSION=3.2
    - DJANGO_VERSION="1.8.*" PYTHON_VERSION=2.7
    - DJANGO_VERSION="1.7.*" PYTHON_VERSION=3.4
    - DJANGO_VERSION="1.7.*" PYTHON_VERSION=3.3
    - DJANGO_VERSION="1.7.*" PYTHON_VERSION=3.2
    - DJANGO_VERSION="1.7.*" PYTHON_VERSION=2.7
