db:
    image: postgres:9.5
test:
    build: .
    command: bash -c "sleep 10; python manage.py test --keepdb"
    links:
        - db
        - selenium
    environment:
        - EXTERNAL_TEST_SERVER=http://livetestserver:8000
        - SELENIUM_HOST=http://selenium:4444/wd/hub
        - PYTHONUNBUFFERED=1
selenium:
    image: selenium/standalone-chrome:2.48.2
    links:
        - livetestserver
livetestserver:
    build: .
    command: bash -c "sleep 10; python manage.py livetestserver 8000 --static"
    environment:
        - PYTHONUNBUFFERED=1
    expose:
        - "8000"
    links:
        - db
