db:
    image: postgres:9.5
test:
    build: .
    command: >
        bash -c "
            while ! (echo > /dev/tcp/db/5432) >/dev/null 2>&1;
                do sleep 1;
            done;
            python manage.py test
        "
    links:
        - db
        - selenium
    environment:
        - EXTERNAL_TEST_SERVER=http://livetestserver:8000
        - SELENIUM_HOST=http://selenium:4444/wd/hub
        - DATABASE_URL=postgres://postgres@db:5432/postgres
selenium:
    image: selenium/standalone-chrome:2.48.2
    links:
        - livetestserver
livetestserver:
    build: .
    command: python manage.py livetestserver 8000 --static
    environment:
        - PYTHONUNBUFFERED=1
        - DATABASE_URL=postgres://postgres@db:5432/test_postgres
    expose:
        - "8000"
    links:
        - db
