db:
    image: postgres:9.5
test:
    build: .
    command: bash -c "sleep 5; python manage.py test --keepdb"
    links:
        - db
        - selenium
    environment:
        - EXTERNAL_TEST_SERVER=http://testserver:8000/
        - SELENIUM_HOST=http://selenium:4444/wd/hub
selenium:
    image: selenium/standalone-chrome:2.48.2
    links:
        - testserver
testserver:
    build: .
    command: bash -c "sleep 5; python manage.py testserver 8000 --static"
    expose:
        - "8000"
    links:
        - db
